name: Mirror to GitLab and Codeberg

on:
  push:
    branches:
      - main 
jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.event.pusher.email }}"

      - name: Push to GitLab
        run: |
          git remote add gitlab https://token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/kampyacr/hola-github.git
          git push gitlab main

